# permissions for end users to edit stackstorms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackstorm-editor-role
rules:
- apiGroups:
  - demo.cloud-castles.com
  resources:
  - stackstorms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.cloud-castles.com
  resources:
  - stackstorms/status
  verbs:
  - get
