# permissions for end users to view stackstorms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stackstorm-viewer-role
rules:
- apiGroups:
  - demo.cloud-castles.com
  resources:
  - stackstorms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.cloud-castles.com
  resources:
  - stackstorms/status
  verbs:
  - get
