apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: st2-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: CloudCastles Stackstorm operator
  displayName: cc-st2-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - stackstorm
  - cloud-castles
  links:
  - name: St2 Operator
    url: https://st2-operator.domain
  maintainers:
  - email: vadim@cloud-castles.com
    name: Vadim Romanov
  maturity: alpha
  provider:
    name: CloudCastles
  version: 0.0.0
